//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.22 at 09:49:27 AM IST 
//


package link.employee;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for employee complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="employee">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="employeeDetails" type="{http://employee.link}employeedetails"/>
 *         &lt;element name="employeeTemporaryAddress" type="{http://employee.link}employeeaddress"/>
 *         &lt;element name="employeePermanentAddress" type="{http://employee.link}employeeaddress"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "employee", propOrder = {
    "employeeDetails",
    "employeeTemporaryAddress",
    "employeePermanentAddress"
})
public class Employee {

    @XmlElement(required = true)
    protected Employeedetails employeeDetails;
    @XmlElement(required = true)
    protected Employeeaddress employeeTemporaryAddress;
    @XmlElement(required = true)
    protected Employeeaddress employeePermanentAddress;

    /**
     * Gets the value of the employeeDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Employeedetails }
     *     
     */
    public Employeedetails getEmployeeDetails() {
        return employeeDetails;
    }

    /**
     * Sets the value of the employeeDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employeedetails }
     *     
     */
    public void setEmployeeDetails(Employeedetails value) {
        this.employeeDetails = value;
    }

    /**
     * Gets the value of the employeeTemporaryAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Employeeaddress }
     *     
     */
    public Employeeaddress getEmployeeTemporaryAddress() {
        return employeeTemporaryAddress;
    }

    /**
     * Sets the value of the employeeTemporaryAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employeeaddress }
     *     
     */
    public void setEmployeeTemporaryAddress(Employeeaddress value) {
        this.employeeTemporaryAddress = value;
    }

    /**
     * Gets the value of the employeePermanentAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Employeeaddress }
     *     
     */
    public Employeeaddress getEmployeePermanentAddress() {
        return employeePermanentAddress;
    }

    /**
     * Sets the value of the employeePermanentAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employeeaddress }
     *     
     */
    public void setEmployeePermanentAddress(Employeeaddress value) {
        this.employeePermanentAddress = value;
    }

}
