
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceImplementationService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:8081/EmployeeWeb?wsdl")
public class WebServiceImplementationService
    extends Service
{

    private final static URL WEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName WEBSERVICEIMPLEMENTATIONSERVICE_QNAME = new QName("http://webservice/", "WebServiceImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/EmployeeWeb?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        WEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public WebServiceImplementationService() {
        super(__getWsdlLocation(), WEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public WebServiceImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public WebServiceImplementationService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEIMPLEMENTATIONSERVICE_QNAME);
    }

    public WebServiceImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public WebServiceImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceImplementation
     */
    @WebEndpoint(name = "WebServiceImplementationPort")
    public WebServiceImplementation getWebServiceImplementationPort() {
        return super.getPort(new QName("http://webservice/", "WebServiceImplementationPort"), WebServiceImplementation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceImplementation
     */
    @WebEndpoint(name = "WebServiceImplementationPort")
    public WebServiceImplementation getWebServiceImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "WebServiceImplementationPort"), WebServiceImplementation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return WEBSERVICEIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
