
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceImplementation", targetNamespace = "http://webservice/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceImplementation {


    /**
     * 
     * @param pinCode
     * @return
     *     returns webservice.EmployeeWebService
     */
    @WebMethod
    @WebResult(name = "employee", partName = "employee")
    @Action(input = "http://webservice/WebServiceImplementation/displayBasedOnPinCodeRequest", output = "http://webservice/WebServiceImplementation/displayBasedOnPinCodeResponse")
    public EmployeeWebService displayBasedOnPinCode(
        @WebParam(name = "pinCode", partName = "pinCode")
        int pinCode);

}
