
package soap.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeWebImplementationService", targetNamespace = "http://service.soap/", wsdlLocation = "http://localhost:8081/employee?wsdl")
public class EmployeeWebImplementationService
    extends Service
{

    private final static URL EMPLOYEEWEBIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEWEBIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName EMPLOYEEWEBIMPLEMENTATIONSERVICE_QNAME = new QName("http://service.soap/", "EmployeeWebImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/employee?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEWEBIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        EMPLOYEEWEBIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public EmployeeWebImplementationService() {
        super(__getWsdlLocation(), EMPLOYEEWEBIMPLEMENTATIONSERVICE_QNAME);
    }

    public EmployeeWebImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEWEBIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public EmployeeWebImplementationService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEWEBIMPLEMENTATIONSERVICE_QNAME);
    }

    public EmployeeWebImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEWEBIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public EmployeeWebImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeWebImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeWebImplementation
     */
    @WebEndpoint(name = "EmployeeWebImplementationPort")
    public EmployeeWebImplementation getEmployeeWebImplementationPort() {
        return super.getPort(new QName("http://service.soap/", "EmployeeWebImplementationPort"), EmployeeWebImplementation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeWebImplementation
     */
    @WebEndpoint(name = "EmployeeWebImplementationPort")
    public EmployeeWebImplementation getEmployeeWebImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.soap/", "EmployeeWebImplementationPort"), EmployeeWebImplementation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEWEBIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw EMPLOYEEWEBIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return EMPLOYEEWEBIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
